module.exports = {
    RESOURSE_ALREADY_EXISTS: 1,
    INVALID_CREDENTIALS: 2,
    REQUIRED_FIELD_MISSING: 3,
    EMPTY_FIELD:    4,
    STOCK_NOT_AVAILABLE: 5,
    RESOURSE_NOT_AVAILABLE: 6,
    INVALID_ROLE: 7,
};